<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.552">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Introduction to Extreme Value Analysis - Peaks-Over-Threshold (POT) Modelling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../evaillustr.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link href="https://fonts.googleapis.com/css?family=Fira+Sans|Merriweather" rel="stylesheet">
<script src="https://kit.fontawesome.com/0fba9333d8.js" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.css">

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Introduction to Extreme Value Analysis">
<meta property="og:description" content="A comprehensive guide to extreme value analysis">
<meta property="og:image" content="https://github.com/diopBachir/tp_eva/blob/master/docs/evaillustr.png">
<meta property="og:site_name" content="Introduction to Extreme Value Analysis">
<meta property="og:locale" content="fr_FR">
<meta name="twitter:title" content="Introduction to Extreme Value Analysis - Peaks-Over-Threshold (POT) Modelling">
<meta name="twitter:description" content="">
<meta name="twitter:image" content="https://github.com/diopBachir/tp_eva/blob/master/docs/evaillustr.png">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="floating nav-fixed slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Introduction to Extreme Value Analysis</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../overview/index.html"> 
<span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../softwaresetup/index.html"> 
<span class="menu-text">Software &amp; Setup</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../blockmaxima/index.html"> 
<span class="menu-text">Block Maxima Approach</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../pot/index.html" aria-current="page"> 
<span class="menu-text">Threshold Exceedance (POT)</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="4">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#libraries" id="toc-libraries" class="nav-link active" data-scroll-target="#libraries"><span class="header-section-number">1</span> Libraries</a></li>
  <li><a href="#the-threshold-exceedance-method" id="toc-the-threshold-exceedance-method" class="nav-link" data-scroll-target="#the-threshold-exceedance-method"><span class="header-section-number">2</span> The threshold exceedance method</a></li>
  <li><a href="#generalized-pareto-gp-distribution" id="toc-generalized-pareto-gp-distribution" class="nav-link" data-scroll-target="#generalized-pareto-gp-distribution"><span class="header-section-number">3</span> Generalized Pareto (GP) distribution</a></li>
  <li><a href="#data-import" id="toc-data-import" class="nav-link" data-scroll-target="#data-import"><span class="header-section-number">4</span> Data import</a></li>
  <li><a href="#sec-thresholdident" id="toc-sec-thresholdident" class="nav-link" data-scroll-target="#sec-thresholdident"><span class="header-section-number">5</span> Choice of the appropriate threshold</a></li>
  <li><a href="#threshold-exceedances-pot-sampling" id="toc-threshold-exceedances-pot-sampling" class="nav-link" data-scroll-target="#threshold-exceedances-pot-sampling"><span class="header-section-number">6</span> Threshold exceedances (POT) sampling</a></li>
  <li><a href="#declustering" id="toc-declustering" class="nav-link" data-scroll-target="#declustering"><span class="header-section-number">7</span> Declustering</a></li>
  <li><a href="#trend-detection" id="toc-trend-detection" class="nav-link" data-scroll-target="#trend-detection"><span class="header-section-number">8</span> Trend detection</a>
  <ul>
  <li><a href="#non-parametric-approach" id="toc-non-parametric-approach" class="nav-link" data-scroll-target="#non-parametric-approach"><span class="header-section-number">8.1</span> Non-parametric approach</a></li>
  <li><a href="#parametric-approach-with-pot-modelling" id="toc-parametric-approach-with-pot-modelling" class="nav-link" data-scroll-target="#parametric-approach-with-pot-modelling"><span class="header-section-number">8.2</span> Parametric approach with POT modelling</a>
  <ul>
  <li><a href="#fit-a-stationary-gp-distribution" id="toc-fit-a-stationary-gp-distribution" class="nav-link" data-scroll-target="#fit-a-stationary-gp-distribution"><span class="header-section-number">8.2.1</span> Fit a stationary GP distribution</a></li>
  <li><a href="#fit-a-non-staionary-gp-distribution" id="toc-fit-a-non-staionary-gp-distribution" class="nav-link" data-scroll-target="#fit-a-non-staionary-gp-distribution"><span class="header-section-number">8.2.2</span> Fit a non-staionary GP distribution</a></li>
  <li><a href="#deviance-test" id="toc-deviance-test" class="nav-link" data-scroll-target="#deviance-test"><span class="header-section-number">8.2.3</span> Deviance test</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#trend-analysis-conclusions" id="toc-trend-analysis-conclusions" class="nav-link" data-scroll-target="#trend-analysis-conclusions"><span class="header-section-number">9</span> Trend analysis conclusions</a></li>
  <li><a href="#flood-quantiles-estimation" id="toc-flood-quantiles-estimation" class="nav-link" data-scroll-target="#flood-quantiles-estimation"><span class="header-section-number">10</span> Flood quantiles estimation</a>
  <ul>
  <li><a href="#stationary-context" id="toc-stationary-context" class="nav-link" data-scroll-target="#stationary-context"><span class="header-section-number">10.1</span> Stationary context</a></li>
  <li><a href="#non-stationary-context" id="toc-non-stationary-context" class="nav-link" data-scroll-target="#non-stationary-context"><span class="header-section-number">10.2</span> Non-Stationary context</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">11</span> References</a></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Peaks-Over-Threshold (POT) Modelling</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="libraries" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Libraries</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(trend)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(extRemes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="the-threshold-exceedance-method" class="level1 page-columns page-full" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> The threshold exceedance method</h1>
<p>The <strong>threshold exceedance method</strong>, often referred to as the <strong>peaks over threshold (POT)</strong>, is based on the <strong><code>Pickands–Balkema–de Haan Theorem</code></strong>, sometimes referred to as the <strong><code>extreme value theorem (EVT) II</code></strong>. <strong><code>EVT II</code></strong> states that for a wide class of underlying distributions, the distribution of excesses above a sufficiently high threshold converges to the <strong><code>Generalized Pareto Distribution (GPD)</code></strong>. The <strong>POT</strong> approach remains relatively under-employed, largely due to the practical complexities involved in its implementation.</p>
<p>Unlike <strong>block maxima approach</strong>, <strong>POT method</strong> is independent of time and instead relies on selecting a cumulative probability level, where data points falling below this threshold are excluded, while values above it are retained for analysis. As in the <strong>block maxima method</strong>, the data are assumed to be independent, so careful extraction of peaks is essential.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>For shorter time series, <strong>POT</strong> approach would be preferable since it allows to use a larger portion of the data, leading to lower uncertainty in estimates. Unlike <strong>block maxima method</strong>, which retains only the largest annual flood (not always extreme!), the <strong>POT method</strong> ensures that all significant flood events are included, even if several occur in the same year.</p>
</div>
</div>
</div></div></section>
<section id="generalized-pareto-gp-distribution" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Generalized Pareto (GP) distribution</h1>
<p><strong>GP</strong> is a continuous two parameters probability distribution used to model exceedances over a high threshold, often referred to as <strong><code>partial duration series (PDS)</code></strong>. The cumulative distribution function (CDF) of the GP distribution is given below, where <span class="math inline">x</span> is the data, <span class="math inline">\alpha &gt; 0</span> is the scale parameter, <span class="math inline">k</span> is the shape parameter, and <span class="math inline">q0</span> the threshold.</p>
<p><span class="math display">
F(x) =
\begin{cases}
1 - \exp\left( -\dfrac{x - q0}{\alpha} \right) &amp; \text{if } k = 0 \\[10pt]
1 - \left( 1 + k \dfrac{(x - q0)}{\alpha} \right)^{-1/k} &amp; \text{if } k \ne 0
\end{cases}
\tag{1}
</span></p>
</section>
<section id="data-import" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Data import</h1>
<p>Will work with the same data used in the <a href="../blockmaxima/index.html#sec-bmdata"><strong>block maxima section</strong></a>, from the <strong><code>La Drôme à Luc-en-Diois</code></strong> station in France.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>filename <span class="ot">=</span> <span class="st">'./data/discharge.csv'</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>Qdata <span class="ot">=</span> <span class="fu">read.csv</span>(filename, <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Year"</span>, <span class="st">"Month"</span>, <span class="st">"Day"</span>, <span class="st">"Q"</span>))  </span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># construct time serie</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>Qdata<span class="sc">$</span>Date <span class="ot">=</span> <span class="fu">paste</span>(Qdata[[<span class="st">"Year"</span>]], Qdata[[<span class="st">"Month"</span>]], Qdata[[<span class="st">"Day"</span>]], <span class="at">sep=</span><span class="st">"-"</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>Qdata<span class="sc">$</span>Date  <span class="ot">=</span> <span class="fu">ymd</span>(Qdata<span class="sc">$</span>Date)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># final time serie</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>Qdata <span class="ot">=</span> Qdata[, <span class="fu">c</span>(<span class="st">"Date"</span>, <span class="st">"Q"</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div id="tbl-pot_loaddata" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pot_loaddata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: First (6) lines of the daily streamflow data for Block-Maxima approach
</figcaption>
<div aria-describedby="tbl-pot_loaddata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Date</th>
<th style="text-align: center;">Q</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">22794</td>
<td style="text-align: center;">2020-12-26</td>
<td style="text-align: center;">2.326204</td>
</tr>
<tr class="even">
<td style="text-align: left;">22795</td>
<td style="text-align: center;">2020-12-27</td>
<td style="text-align: center;">2.173519</td>
</tr>
<tr class="odd">
<td style="text-align: left;">22796</td>
<td style="text-align: center;">2020-12-28</td>
<td style="text-align: center;">2.193727</td>
</tr>
<tr class="even">
<td style="text-align: left;">22797</td>
<td style="text-align: center;">2020-12-29</td>
<td style="text-align: center;">2.090440</td>
</tr>
<tr class="odd">
<td style="text-align: left;">22798</td>
<td style="text-align: center;">2020-12-30</td>
<td style="text-align: center;">1.966944</td>
</tr>
<tr class="even">
<td style="text-align: left;">22799</td>
<td style="text-align: center;">2020-12-31</td>
<td style="text-align: center;">1.854676</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-streamflow_ts" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-streamflow_ts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-streamflow_ts-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-streamflow_ts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Daily streamflow time serie.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="sec-thresholdident" class="level1 page-columns page-full" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Choice of the appropriate threshold</h1>
<p>Choosing the appropriate threshold involves balancing <strong><code>bias</code></strong> and <strong><code>variance</code></strong>: setting it <strong>lower</strong> provides more data but risks introducing bias, whereas setting it <strong>too high</strong> reduces the data available, increasing uncertainty <span class="citation" data-cites="gilleland2016extremes">(<a href="#ref-gilleland2016extremes" role="doc-biblioref">Gilleland &amp; Katz, 2016</a>)</span>. Like choosing block size in the Block Maxima method, selecting a threshold in the POT approach aims to capture true extremes, while maintaining sufficient data for robust analysis. Even if several methods to select the threshold are available in the litterature, it is still a subjective task. The most common practice is to use graphical methods <span class="citation" data-cites="coles2001">(<a href="#ref-coles2001" role="doc-biblioref">Coles, 2001</a>)</span>.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Interpreting these plots often requires a certain degree of <strong>subjective judgment</strong>, as clear-cut decisions about threshold suitability are rarely evident.</p>
</div>
</div>
</div><div class="">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The threshold process can be automated (see <span class="citation" data-cites="solari2017">Solari et al. (<a href="#ref-solari2017" role="doc-biblioref">2017</a>)</span>) for details.</p>
</div>
</div>
</div></div>
<p>One way to perform threshold selection, is a focused analysis within an specfic interval. <span class="citation" data-cites="gilleland2016extremes">Gilleland &amp; Katz (<a href="#ref-gilleland2016extremes" role="doc-biblioref">2016</a>)</span> proposes a procedure, implemented in the <strong><code>{extRemes}</code></strong> ecosystem, that repeatedly fits the GP distribution to the data across a sequence of threshold values, while also providing measures of variability. The idea, as they stated in their tutorial, is to identify the lowest threshold above which the fitted model remains stable, meaning that increasing the threshold further does not significantly change the results, apart from expected variation within the uncertainty bounds.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong><code>{extRemes}</code></strong> library provides the <strong><code>mrlplot(...)</code></strong> function to produce the <strong>MRL</strong> plot.</p>
</div>
</div>
</div></div><div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> Qdata<span class="sc">$</span>Q</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">threshrange.plot</span>(x, <span class="at">r =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">30</span>), <span class="at">nint=</span><span class="dv">25</span>, <span class="at">na.action=</span>na.omit, <span class="at">set.panels=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><a href="#fig-thrangeplot" class="quarto-xref">Figure&nbsp;2</a> illustrates how the shape and modified scale parameters of the GP distribution evolve across a range of threshold values. The parameters appear to stabilize around a threshold of <strong>10</strong>, while higher thresholds (from 15) exhibit increased variability, likely due to the decreasing number of exceedances.</p>
<div id="fig-thrangeplot" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-thrangeplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-thrangeplot" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-thrangeplot-1" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-thrangeplot-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-thrangeplot-1.png" class="img-fluid figure-img" data-ref-parent="fig-thrangeplot" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-thrangeplot-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Variability of the (reparametrized) scale parameter
</figcaption>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-thrangeplot" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-thrangeplot-2" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-thrangeplot-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-thrangeplot-2.png" class="img-fluid figure-img" data-ref-parent="fig-thrangeplot" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-thrangeplot-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Variability of the shape parameter
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-thrangeplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Threshold range plots showing the variability of GP distribution parameters across different threshold values.
</figcaption>
</figure>
</div>
<p>Another most widely used graphical tools: the <strong><code>Mean Residual Life (MRL) plot</code></strong>. <strong>MRL</strong> is based on the theoretical mean of the GP <span class="citation" data-cites="ribatet2011pot">(<a href="#ref-ribatet2011pot" role="doc-biblioref">Ribatet, 2011</a>)</span>, and helps assess the adequacy of a threshold for GP distribution modeling. The MRL plot displays the average excess over a range of thresholds, defined as the mean of the exceedances above a given threshold <span class="math inline">q</span>. If the exceedances above a certain threshold follow a GP distribution, the <strong>MRL</strong> function should appear approximately linear beyond that point (see <span class="citation" data-cites="gilleland2016extremes">Gilleland &amp; Katz (<a href="#ref-gilleland2016extremes" role="doc-biblioref">2016</a>)</span> for details). Thus, identifying a linear region in the plot guide the selection of a suitable threshold. Despite its simplicity, the <strong>MRL</strong> plot provides a useful diagnostic to balance threshold stability and GP distribution fit (cf. <span class="citation" data-cites="coles2001">Coles (<a href="#ref-coles2001" role="doc-biblioref">2001</a>)</span>, Section 4.3.1).</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong><code>{extRemes}</code></strong> library provides the <strong><code>mrlplot(...)</code></strong> function to produce the <strong>MRL</strong> plot.</p>
</div>
</div>
</div></div><p>For diagnosing an appropriate choice, the chunk above produces the <strong>MRL</strong> plot with a <strong>95% confidence intervals (CIs)</strong>. <strong>CIs</strong> are based on the <strong>normal df</strong> for the <strong>mean excesses</strong>. The <strong>MRL</strong> plot is expected to exhibit <strong>approximately linear</strong> behavior above a suitable threshold <span class="citation" data-cites="coles2001">(<a href="#ref-coles2001" role="doc-biblioref">Coles, 2001</a>)</span>. As shown in <a href="#fig-mrlplot" class="quarto-xref">Figure&nbsp;3</a>, the threshold <span class="math inline">q = 10</span> appears appropriate, since the linearity assumption is reasonably satisfied beyond this point.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> Qdata<span class="sc">$</span>Q</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mrlplot</span>(x, <span class="at">na.action=</span>na.omit)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="dv">10</span>, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)  <span class="co"># Vertical line at q = 10</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-mrlplot" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mrlplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-mrlplot-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mrlplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: The threshold selection: the mean residual life (mean excess) plot with dashed green lines indicating the 95% confidence intervals for the mean excesses. The vertical red dashed line indicates the threshold <span class="math inline">q = 10</span>.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="threshold-exceedances-pot-sampling" class="level1 page-columns page-full" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Threshold exceedances (POT) sampling</h1>
<p>We need to extract all exceedances above the threshold for further analysis. <a href="#fig-allexcedences" class="quarto-xref">Figure&nbsp;4</a> show daily streamflow time serie with all exceedances above the threshold.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># extract all flow values above the threshold and sort by date</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>thres <span class="ot">=</span> <span class="dv">10</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>all_exceedances <span class="ot">=</span> Qdata <span class="sc">|&gt;</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">filter</span>(Q <span class="sc">&gt;</span> thres) <span class="sc">|&gt;</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">arrange</span>(Date)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-allexcedences" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-allexcedences-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-allexcedences-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-allexcedences-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Streamflow time serie with all exceedances (red dots) above the threshold (horizontal blue line)
</figcaption>
</figure>
</div>
</div>
</div>
<p>The <strong>correlogram</strong> (<a href="#fig-acfplot_pot" class="quarto-xref">Figure&nbsp;5</a>) shows that the extracted peaks are autocorrelated for lag 1 and 2. This reflects dependence between consecutive peaks, and even one time step apart, values still influence each other.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-acfplot_pot" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-acfplot_pot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-acfplot_pot-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-acfplot_pot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Autocorrelation (at different lags) of peaks over the selected threshold. The red line represents the 95% confidence interval.
</figcaption>
</figure>
</div>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is expected, as peaks are likely to be close to each — i.e., a peak is often followed by another peak of similar magnitude within the next 1–2 time steps.</p>
</div>
</div>
</div></div><p>We can confirm the dependance of the threshold exceedances with the Wald-Wolfowitz independence test <span class="citation" data-cites="wald_test_1940">(<a href="#ref-wald_test_1940" role="doc-biblioref">Wald &amp; Wolfowitz, 1940</a>)</span> (see <a href="../blockmaxima/index.html#sec-wwtest"><strong>autocorrelation section</strong></a>) performed with the chunk below. The test summary indicates that the data are highly autocorrelated, whith a <strong>very low p-value (&lt; 2.2e-16)</strong>, supporting the rejection, with high confidence, of the null hyposthesis that the data are independent.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Wald-Wolfowitz test for independence and stationarity

data:  x
z = 13.377, n = 800, p-value &lt; 2.2e-16
alternative hypothesis: The series is significantly different from 
 independence and stationarity</code></pre>
</div>
</div>
</section>
<section id="declustering" class="level1 page-columns page-full" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Declustering</h1>
<p>The naive selection of events above a specfic threshold may lead to dependent (or auto-correlated) events. It’s important that the exceedances over the threshold are independent because <strong>extreme value theory</strong> assumes each event is separate and not part of the same physical phenomenon (like one long flood event). However, floods and other hydrological extremes often occur in clusters due to persistent weather systems. To ensure independence, a process called <strong><code>de-clustering</code></strong> is often applied after sampling events above the selected threshold.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong><code>Declustering</code></strong> is essential for satisfying the <strong>independence assumption</strong> required by <strong>extreme value analysis</strong>.</p>
</div>
</div>
</div></div><p><strong><code>De-clustering</code></strong> is the process of identifying and retaining independent extreme events from a time serie by removing clustered values. A two-rules <strong><code>de-clustering</code></strong> method is commonly applied in the litterature to separate dependent events: (i) <strong><code>time separation rule</code></strong> and (ii) <strong><code>magnitude differential rule</code></strong> <span class="citation" data-cites="lang1999">(<a href="#ref-lang1999" role="doc-biblioref">Lang et al., 1999</a>)</span>.</p>
<div id="fig-decluster" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-decluster-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/declust_modern.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-decluster-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Inter-flood duration criteria (adapted from <span class="citation" data-cites="lang1999">Lang et al. (<a href="#ref-lang1999" role="doc-biblioref">1999</a>)</span>). <span class="math inline">θ</span> represents a minimum number of days between two consecutive peaks. <span class="math inline">(Xs)_1</span> and <span class="math inline">(Xs)_2</span> are respectively the first and second peaks, and <span class="math inline">X_{min}</span> is the minimum flow value between the two peaks.
</figcaption>
</figure>
</div>
<ol type="1">
<li><p><strong><code>Time separation rule:</code></strong> a minimum number of days between successive peaks. This criterion can be computed with the following equation <span class="citation" data-cites="wrc1975">(<a href="#ref-wrc1975" role="doc-biblioref">USWRC, 1975</a>)</span>: <span class="math display">Ts = 5days + log(A)</span> where <span class="math inline">A</span> is the catchment area. Let <span class="math inline">θ</span> represents the minimum number of days between two consecutive peaks:</p>
<ul>
<li>If <span class="math inline">θ &lt; Ts</span> → <strong><code>REJECT</code></strong> the second peak.</li>
</ul></li>
</ol>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This <strong>time separation rule</strong> assumes that larger watersheds require more time for floods to travel through and fully drain from the system.</p>
</div>
</div>
</div></div><ol start="2" type="1">
<li><p><strong><code>Magnitude differential rule:</code></strong> flow should drop below a certain fraction of the smaller peak between events. <span class="citation" data-cites="cunnane1979">Cunnane (<a href="#ref-cunnane1979" role="doc-biblioref">1979</a>)</span> propose the following condition, where <span class="math inline">X_{min}</span> is the minimum flow value between the two peaks, and <span class="math inline">(Xs)_1</span> is the first peak:</p>
<ul>
<li>If <span class="math inline">X_{min} &gt; (2/3)(Xs)_1</span> → <strong><code>REJECT</code></strong> the second peak <span class="math inline">(Xs)_2</span>.</li>
</ul></li>
</ol>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Cunnane’s condition</strong> assesses whether the flood “drops sufficiently” after the first peak. If it not, it is considered a continuation of the same flood event.</p>
</div>
</div>
</div></div><p>These two rules described above not alternatives to each other, but <strong>complementary</strong>. That is, both conditions should be satisfied for an event to be considered a separate flood. We will first apply the <strong>time separation rule</strong> to ensure enough time passes for the basin to drain fully between events, and then the <strong>magnitude differential rule</strong> to ensures a significant drop in flow indicating a “new flood wave”.</p>
<p>We will <strong>decluster</strong> our time serie using the <strong>threshold value of 10</strong>, as identified in <a href="#sec-thresholdident" class="quarto-xref">Section&nbsp;5</a>. The Area of the studied catchment is <span class="math inline">194 km²</span>, as described in the <a href="https://www.hydro.eaufrance.fr/sitehydro/V4214010/fiche">HydroPortail website (here)</a></p>
<p>We first define a function which takes as arguments the <strong>streamflow data</strong>, the <strong>peak-over-threshold</strong> value, and the <strong>drainage basin area</strong>, performs the <strong>temporal declustering technique</strong>:</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#' Select Time-Separated Peaks (De-clustering)</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co">#'</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co">#' Identifies independent flood peaks by applying a minimum time separation rule </span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">#' between exceedances over a given threshold. This is commonly used to de-cluster </span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co">#' peaks in the context of Peaks Over Threshold (POT) modeling.</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co">#'</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param data A data frame containing at least `Date` and `Flow` columns.</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param threshold Numeric. The flow threshold above which a value is considered an exceedance.</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param Area Numeric. Catchment Area.</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co">#'</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="co">#' @return A data frame of de-clustered peaks (exceedances separated by at least `Ts` days).</span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>time_sep_declust <span class="ot">=</span> <span class="cf">function</span>(data, threshold, Area) </span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>{  </span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># convert Area from km²to Miles²</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>  A_miles <span class="ot">=</span> Area<span class="sc">*</span><span class="fl">0.386</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>  <span class="co"># compute the number of days required (Ts)</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>  Ts <span class="ot">=</span> <span class="fu">ceiling</span>(<span class="dv">5</span> <span class="sc">+</span> <span class="fu">log</span>(A_miles))</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Filter flow values above the threshold and sort by date</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>  exceedances <span class="ot">=</span> data <span class="sc">|&gt;</span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>                <span class="fu">filter</span>(Q <span class="sc">&gt;</span> threshold) <span class="sc">|&gt;</span></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>                <span class="fu">arrange</span>(Date)</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>  <span class="co"># initialize first exceedance as the first independent peak</span></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>  kept_peaks <span class="ot">=</span> exceedances[<span class="dv">1</span>, , drop<span class="ot">=</span><span class="cn">FALSE</span>]</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>  last_peak_date <span class="ot">=</span> exceedances<span class="sc">$</span>Date[<span class="dv">1</span>]</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Loop through remaining exceedances to apply the time-separation rule</span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span><span class="fu">nrow</span>(exceedances)) </span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>  {</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>    current_date <span class="ot">=</span> exceedances<span class="sc">$</span>Date[i]</span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">as.numeric</span>(current_date <span class="sc">-</span> last_peak_date) <span class="sc">&gt;=</span> Ts) {</span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a>      kept_peaks <span class="ot">=</span> <span class="fu">bind_rows</span>(kept_peaks, exceedances[i, , <span class="at">drop=</span><span class="cn">FALSE</span>])</span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a>      last_peak_date <span class="ot">=</span> current_date</span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb7-39"><a href="#cb7-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-40"><a href="#cb7-40" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Return the de-clustered peaks</span></span>
<span id="cb7-41"><a href="#cb7-41" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(kept_peaks)</span>
<span id="cb7-42"><a href="#cb7-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-43"><a href="#cb7-43" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We can now apply our temporal declustering function to the POT serie. The Area of the studied catchment is <span class="math inline">194 km²</span>, as described in the <a href="https://www.hydro.eaufrance.fr/sitehydro/V4214010/fiche">HydroPortail website (here)</a></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># time separation</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>peaks_time_declust <span class="ot">=</span> <span class="fu">time_sep_declust</span>(<span class="at">data=</span>Qdata, <span class="at">threshold=</span>thres, <span class="at">Area=</span>area)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-temporaldeclust" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-temporaldeclust-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-temporaldeclust-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-temporaldeclust-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Streamflow time serie with all exceedances (red dots) above the threshold (horizontal blue line), along with the declustered peaks (green crosses) using the time-separation rule.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Now, we apply the <strong>magnitude diffrential rule</strong> to the temporally declustered peaks. To achieve this, we need to define aother function which takes as arguments the <strong>temporally declustered data</strong>, the the <strong>original streamflow data</strong>, and the <strong>fraction</strong> to compute magnitude diffrential, set to <strong>2/3</strong>.</p>
<div class="cell">
<details class="code-fold">
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#' Filter peaks based on intervening flow magnitude</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co">#'</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co">#' This function removes clustered peaks in a time series based on the magnitude </span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">#' difference between consecutive peaks. Specifically, a peak is discarded if </span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co">#' the minimum flow between it and the previous peak is greater than a specified </span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co">#' fraction (`frac`) of the previous peak's magnitude.</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co">#'</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param data A data frame containing temporallydeclustered peaks, with columns `Date` and `Flow`.</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param original_data The full original time series with at least `Date` and `Flow` columns.</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="co">#' @param frac A numeric value (default is 2/3). A peak is discarded if the minimum </span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="co">#'        flow between it and the previous peak is greater than `frac * previous_peak`.</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co">#'</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="co">#' @return A filtered data frame of peaks after magnitude-based declustering.</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>magnitude_diff_declust <span class="ot">=</span> <span class="cf">function</span>(data, original_data, <span class="at">frac =</span> <span class="dv">2</span><span class="sc">/</span><span class="dv">3</span>) </span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Return as-is if there is only one or no peak</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span> (<span class="fu">nrow</span>(data) <span class="sc">&lt;=</span> <span class="dv">1</span>) <span class="fu">return</span>(data)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Logical vector to mark which peaks to keep</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>  keep <span class="ot">=</span> <span class="fu">rep</span>(<span class="cn">TRUE</span>, <span class="fu">nrow</span>(data))</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Iterate through peaks, comparing each with the previous one</span></span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">2</span><span class="sc">:</span><span class="fu">nrow</span>(data)) {</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>    peak1_date <span class="ot">=</span> data<span class="sc">$</span>Date[i <span class="sc">-</span> <span class="dv">1</span>]</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a>    peak2_date <span class="ot">=</span> data<span class="sc">$</span>Date[i]</span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Extract the flow values between two peaks from the full time series</span></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>    in_between <span class="ot">=</span> original_data <span class="sc">|&gt;</span></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(Date <span class="sc">&gt;</span> peak1_date, Date <span class="sc">&lt;</span> peak2_date)</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>    <span class="co"># If no data in between, keep the current peak</span></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">nrow</span>(in_between) <span class="sc">==</span> <span class="dv">0</span>) <span class="cf">next</span></span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Safely calculate minimum flow in the interval</span></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>    flows_between <span class="ot">=</span> in_between<span class="sc">$</span>Flow</span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>    flows_between <span class="ot">=</span> flows_between[<span class="sc">!</span><span class="fu">is.na</span>(flows_between)]</span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Skip if no valid flow values between peaks</span></span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">length</span>(flows_between) <span class="sc">==</span> <span class="dv">0</span>) <span class="cf">next</span></span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>    Xmin <span class="ot">=</span> <span class="fu">min</span>(flows_between)</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>    Xs1 <span class="ot">=</span> data<span class="sc">$</span>Flow[i <span class="sc">-</span> <span class="dv">1</span>]</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Skip if previous peak flow is NA or missing</span></span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">is.na</span>(Xs1)) <span class="cf">next</span></span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Discard current peak if in-between flow is too high</span></span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (Xmin <span class="sc">&gt;</span> frac <span class="sc">*</span> Xs1) {</span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a>      keep[i] <span class="ot">=</span> <span class="cn">FALSE</span></span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Return only the peaks that meet the magnitude difference criterion</span></span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a>  <span class="fu">return</span>(data[keep, ])</span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><a href="#fig-finaldeclust" class="quarto-xref">Figure&nbsp;8</a> show that the additional declustering step after temporal separation rule is not necessary, as the any peak is discarded by this second rule.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># magnitude differential</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>peaks_final <span class="ot">=</span> <span class="fu">magnitude_diff_declust</span>(<span class="at">data=</span>peaks_time_declust, <span class="at">original_data=</span>Qdata)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-finaldeclust" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-finaldeclust-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-finaldeclust-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-finaldeclust-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Streamflow time serie with with the declustered peaks (purple dots) using the magnitude difference rule.
</figcaption>
</figure>
</div>
</div>
</div>
<p><a href="#fig-acfdeclust" class="quarto-xref">Figure&nbsp;9</a> shows the <strong>correlogram</strong> computed on the declustered peaks. There is no statistically significant autocorrelation beyond lag 0. Thus, the declustered peaks can be considered approximately independent.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-acfdeclust" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-acfdeclust-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-acfdeclust-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-acfdeclust-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Autocorrelation (at different lags) of <strong>declustered</strong> peaks value. The red line represents the 95% confidence interval.
</figcaption>
</figure>
</div>
</div>
</div>
<p>To further assess the independence of the declustered peaks, we apply the Wald-Wolfowitz independence test. From the results displayed below, we conclude that <strong>the declustering worked well</strong>, as we now fall to reject the null hypothesis of independance, with <strong>p.value equal to 0.2301</strong>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Wald-Wolfowitz test for independence and stationarity

data:  x
z = 1.2001, n = 219, p-value = 0.2301
alternative hypothesis: The series is significantly different from 
 independence and stationarity</code></pre>
</div>
</div>
</section>
<section id="trend-detection" class="level1 page-columns page-full" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Trend detection</h1>
<section id="non-parametric-approach" class="level2 page-columns page-full" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="non-parametric-approach"><span class="header-section-number">8.1</span> Non-parametric approach</h2>
<p>As for the <strong>block maxima</strong> approach (see <a href="../blockmaxima/index.html#sec-trend">trend detection section</a>), we can also apply the <strong>non-parametric Mann-Kendall</strong> trend test for monotonic trend detection. See the <a href="../blockmaxima/index.html#sec-mk">Mann-Kendall section</a> for the complete algorithm of the test. In the chunk below, we use the <strong><code>mk.test(...)</code></strong> function from the <strong><code>{trend}</code></strong> library to perform the trend test.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong><code>p.value = 0.5059:</code></strong> there is not enough statistical evidence to conclude that a significant trend exists in the threshold exceedances serie.</p>
<p><strong><code>tau = -3.041649e-02:</code></strong> indicates a weak or no trend.</p>
<p><strong><code>z = -0.66528:</code></strong> suggests a potential decreasing trend, but the trend is not significant.</p>
</div>
</div>
</div></div><div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># perform Mann-Kendall trend test</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>mktest <span class="ot">=</span> trend<span class="sc">::</span><span class="fu">mk.test</span>(<span class="at">x =</span> peaks_final<span class="sc">$</span>Q)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mktest)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Mann-Kendall trend test

data:  peaks_final$Q
z = -0.66528, n = 219, p-value = 0.5059
alternative hypothesis: true S is not equal to 0
sample estimates:
            S          varS           tau 
-7.220000e+02  1.174512e+06 -3.041649e-02 </code></pre>
</div>
</div>
<p>The snippet below computes the absolute and relative <strong>Sen’s slope</strong>, to quantify the magnitude of trend in the POT data as both a raw rate of change and a percentage relative to the mean. See the <a href="../blockmaxima/index.html#sec-sens">Sen’s slope section</a> for the complete algorithm and the user-defined function <strong><code>sens_slope_percent(...)</code></strong> we apply below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute Sen's slope as a percentage change</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sens_slope_percent</span>(peaks_final<span class="sc">$</span>Q)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Absolute Sen's slope: -0.0017
P-value: 0.5059
Relative trend rate: -0.01%</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Relative Sen’s slope
</div>
</div>
<div class="callout-body-container callout-body">
<p>The threshold exceedances serie show a slight decreasing trend with a <strong>slope of -0.0017 rate</strong>, which is equivalent to <strong>−0.01% relative to its long-term average</strong>. Yet, this negative trend is not significative given the <strong>p-value of 0.5059</strong>.</p>
</div>
</div>
</div></div></section>
<section id="parametric-approach-with-pot-modelling" class="level2 page-columns page-full" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="parametric-approach-with-pot-modelling"><span class="header-section-number">8.2</span> Parametric approach with POT modelling</h2>
<section id="fit-a-stationary-gp-distribution" class="level3 page-columns page-full" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="fit-a-stationary-gp-distribution"><span class="header-section-number">8.2.1</span> Fit a stationary GP distribution</h3>
<p>As we have already seen in the previous section, the GP distribution is the most appropriate distribution to model threshold exceedances. As explained by <span class="citation" data-cites="gilleland2016extremes">Gilleland &amp; Katz (<a href="#ref-gilleland2016extremes" role="doc-biblioref">2016</a>)</span> in their paper, an important additional consideration when using the POT approach is the <strong>rate of exceedance</strong> — that is, how often values exceed the chosen threshold. While this rate does not affect the fitting of the GP model itself, it is crucial for calculating return levels, which require scaling the model to real-world time units.</p>
<p>The <strong>exceedance rate</strong> should be passed the <strong><code>time.units</code></strong> argument in the <strong><code>fevd(...)</code></strong> function. Since our goal is to estimate annual return levels, we must specify the average number of threshold exceedances per year (i.e., the average number of flood events per year in our dataset).</p>
<p><a href="#fig-finaldeclust" class="quarto-xref">Figure&nbsp;8</a> shows that the number of events per year varies — some years experience multiple flood events, while others have none. Therefore, a reasonable approach is to use the empirical average number of exceedances per year over the entire study period as the value for <strong><code>time.units</code></strong>. The snippet below shows how to calculate this rate.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute the average number of threshold exceedances per year</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>peaks_final<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">year</span>(peaks_final<span class="sc">$</span>Date)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>n_years <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">unique</span>(peaks_final<span class="sc">$</span>year))</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>n_events <span class="ot">&lt;-</span> <span class="fu">nrow</span>(peaks_final)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>units <span class="ot">&lt;-</span> n_events <span class="sc">/</span> n_years</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Optional: print it nicely</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Average number of events per year:"</span>, <span class="fu">round</span>(units, <span class="dv">2</span>), <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Average number of events per year: 3.71 </code></pre>
</div>
</div>
<p>Now, we can fit our <strong>GP model</strong> to the POT data. The workflow is same as the block maxima models (GEV and Gumbel), and same tools can be used to estimates the GP parameters. In the chunk below, we use the <strong><code>{extRemes}</code></strong> library again to fit the GP distribution to our partial duration serie in a statinary context.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit the stationary GP distribution to the PDS</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(extRemes)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>thres <span class="ot">=</span> <span class="dv">10</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>x <span class="ot">=</span> peaks_final<span class="sc">$</span>Q</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>sgp_fit <span class="ot">=</span> <span class="fu">fevd</span>(x, <span class="at">type=</span><span class="st">"GP"</span>, <span class="at">method=</span><span class="st">"GMLE"</span>, <span class="at">threshold=</span>thres, <span class="at">time.units =</span> <span class="fu">paste0</span>(units,<span class="st">"/year"</span>))</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co"># show summary of the fit</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="fu">pretty_fit_summary</span>(sgp_fit, <span class="st">"GP"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>=== GP  Fit Summary ===

Estimated Parameters:
 scale  shape 
3.6496 0.3099 

Model Fit Criteria:
LogLik: -570.53</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The only thing that change here, comared to the <strong>block maxima models</strong>, is the additional <strong>threshold value</strong> and the <strong>time.units</strong> arguments passed to the <strong><code>fevd(...)</code></strong> function, which is the same as the threshold used in the declustering process. The <strong><code>pretty_fit_summary(...)</code></strong> is defined in the <a href="../blockmaxima/index.html#sec-utils">block maxima section</a>.</p>
</div>
</div>
</div></div><p><a href="#fig-gpfitdiag-stationary" class="quarto-xref">Figure&nbsp;10</a> displays the diagnostics from the GP distribution fitted to the partial duration serie: density plot of empirical data and fitted GP df (top-left), and quantiles from a sample drawn from the fitted GP against the empirical data quantiles with 95% confidence bands (top-right).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># show diagnostic plots of the GP distribution fitting</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>))</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sgp_fit, <span class="at">type=</span><span class="st">"density"</span>, <span class="at">main=</span><span class="st">"(a) Density plot"</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sgp_fit, <span class="at">type=</span><span class="st">"qq2"</span>, <span class="at">main=</span><span class="cn">NULL</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">title</span>(<span class="at">main=</span><span class="st">"(b) Q-Q plot"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="fig-gpfitdiag-stationary" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-gpfitdiag-stationary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-gpfitdiag-stationary-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-gpfitdiag-stationary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Diagnostic plots for the General Pareto (GP) distribution fitted to the threshold exceedances serie in a stationary context.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="fit-a-non-staionary-gp-distribution" class="level3 page-columns page-full" data-number="8.2.2">
<h3 data-number="8.2.2" class="anchored" data-anchor-id="fit-a-non-staionary-gp-distribution"><span class="header-section-number">8.2.2</span> Fit a non-staionary GP distribution</h3>
<p>As for the <strong>block maxima models</strong>, one way to account for non-stationary is to incorporate covariates within the parameters of the distributions in a <strong><code>regression-like manner</code></strong>. To perform <strong>parametric trend detection</strong> with the <strong>GP distribution</strong>, we model the <strong><code>scale parameter (σ)</code></strong> as a function of time, transforming the model into a <strong><code>non-stationary GP</code></strong>. The scale parameter of the non-stationnary GP distribution is computed as follow: <span class="math display">
\sigma (t) = \sigma 0 + \sigma 1·t \tag{2}
</span> where <span class="math inline">\sigma</span> is the time-dependant scale parameter of the GP distribution, <span class="math inline">t</span> is the time index, <span class="math inline">\sigma 0</span> is the intercept, and <span class="math inline">\sigma 1</span> is the slope.</p>
<p>The chunk below use the <strong><code>{extRemes}</code></strong> library to fit the <strong><code>Non-Stationary GP (NS-GP) distribution</code></strong> to our <strong>Partial Duration Serie</strong> extracted earlier. Unfortunately, most of the <strong><code>extRemes</code></strong> diagnostic plots currently are not available for non-stationary POT models.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># set threshold</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>thres <span class="ot">=</span> <span class="dv">10</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="co"># use time index for non-stationary context fitting</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>peaks_final<span class="sc">$</span>scale_cov <span class="ot">=</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(peaks_final)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="co"># fit the GP distribution to the PDS</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>PDS <span class="ot">=</span> <span class="fu">data.frame</span>(peaks_final)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>nsgp_fit <span class="ot">=</span> <span class="fu">fevd</span>(<span class="at">x=</span>Q, <span class="at">scale.fun=</span><span class="sc">~</span>scale_cov, <span class="at">data=</span>PDS, <span class="at">type=</span><span class="st">"GP"</span>, </span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">method=</span><span class="st">"GMLE"</span>, <span class="at">threshold=</span>thres, <span class="at">time.units=</span><span class="fu">paste0</span>(units,<span class="st">"/year"</span>))</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a><span class="co"># show summary of the fit</span></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="fu">pretty_fit_summary</span>(nsgp_fit, <span class="st">"Non-Stationary GP"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>=== Non-Stationary GP  Fit Summary ===

Estimated Parameters:
 sigma0  sigma1   shape 
 4.1064 -0.0040  0.3066 

Model Fit Criteria:
LogLik: -570.21</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
NS-GP parameters
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong><code>sigma0 = σ0 = 4.1064:</code></strong> is the <strong>intercept</strong> of the time-varying GP scale parameter. It represents the base scale of the distribution (often the start of the time series).</p>
<p><strong><code>sigma1 = σ1 = -0.0040:</code></strong> is the <strong>slope</strong> of the scale parameter with respect to time. This negative value suggests that extreme values are becoming less variable (narrower tail) over time.</p>
<p><strong><code>shape = 0.3066:</code></strong> controls the <strong>heaviness</strong> of the tail of the GP distribution. The positive value (ξ &gt; 0) suggests a heavy (Fréchet) tail (i.e., the probability of very large exceedances decays slowly).</p>
</div>
</div>
</div></div></section>
<section id="deviance-test" class="level3 page-columns page-full" data-number="8.2.3">
<h3 data-number="8.2.3" class="anchored" data-anchor-id="deviance-test"><span class="header-section-number">8.2.3</span> Deviance test</h3>
<p>The <strong>non-parametric Mann-Kendall</strong> test indicates a non-significant trend in the POT values. With <strong>parametric methods</strong>, the significance of a temporal trend is based on a <strong>deviance test</strong> between a non-stationary (or more complex) model and a stationary one. The <strong>deviance test</strong>, or <strong>Likelihood Ratio (LR)</strong> test, compares two nested models — a simpler (stationary) model and a more complex (non-stationary) model.</p>
<p>The null hypothesis of the <strong>deviance test</strong> is that the <strong>simpler model is sufficient — i.e., no trend</strong> (e.g., the GP scale parameter is constant over time). See the <a href="../blockmaxima/index.html##sec-deviancetest">Deviance test Section</a> for the mathematical details.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>We try just to answer this question: Does the more <strong>complex non-stationary GP model</strong> provide a significantly better fit to the data than the <strong>simpler stationary GP model</strong>?</p>
</div>
</div>
</div></div><p>To perform the <strong><code>Deviance test</code></strong>, we can use the <strong><code>lr.test(...)</code></strong> of the <strong><code>{extRemes}</code></strong>. This function just requires the previous fitted objects of class <strong><code>“fevd”</code></strong> from the <strong><code>fevd(...)</code></strong> function:</p>
<ul>
<li><strong><code>sgp_fit</code></strong>: model with fewer parameters (stationary GP model)</li>
<li><strong><code>nsgp_fit</code></strong>model with more parameters (non-stationary GP model)</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># applying the Deviance test</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lr.test</span>(<span class="at">x=</span>sgp_fit, <span class="at">y=</span>nsgp_fit, <span class="at">alpha=</span><span class="fl">0.05</span>, <span class="at">df=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Likelihood-ratio Test

data:  xQ
Likelihood-ratio = 0.64953, chi-square critical value = 3.8415, alpha =
0.0500, Degrees of Freedom = 1.0000, p-value = 0.4203
alternative hypothesis: greater</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Interpretation
</div>
</div>
<div class="callout-body-container callout-body">
<p>🚫 We fail to reject the null hypothesis.</p>
<ul>
<li><strong><code>D-statistic (0.65)</code></strong> much smaller than the <strong><code>critical value (3.84)</code></strong>.</li>
<li><strong><code>p-value (0.4203)</code></strong> much larger than the <strong><code>significance level (0.05)</code></strong>.</li>
</ul>
</div>
</div>
</div></div></section>
</section>
</section>
<section id="trend-analysis-conclusions" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> Trend analysis conclusions</h1>
<p>🔎 <strong>Trend Detection Methods Used</strong></p>
<ul>
<li>Parametric: <strong><code>Non-stationary GP model</code></strong> with <strong>time-varying scale parameter</strong></li>
<li>Non-parametric: <strong><code>Mann-Kendall test</code></strong></li>
</ul>
<p>🚫 <strong>No Significant Trend Detected</strong></p>
<ul>
<li>Both methods consistently indicate <strong>no statistically significant trend</strong> in the POT serie.</li>
<li>The <strong>Likelihood Ratio Test</strong> showed a high p-value (0.4203), and both the <strong>Mann-Kendall test</strong> and the <strong>Sen’s slope</strong> similarly returned a non-significant result, with a p-value of 0.5059 and 0.5059, respectively.</li>
</ul>
<p>✅ <strong>Modeling Implication</strong></p>
<ul>
<li>The results support the use of a stationary GP model.</li>
<li>There is <strong>no strong evidence</strong> of temporal change in flood extremes over the study period.</li>
</ul>
</section>
<section id="flood-quantiles-estimation" class="level1 page-columns page-full" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> Flood quantiles estimation</h1>
<section id="stationary-context" class="level2 page-columns page-full" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="stationary-context"><span class="header-section-number">10.1</span> Stationary context</h2>
<p>To estimate <strong>return levels</strong> for given <strong>return periods</strong>, we can use the <strong><code>return.level(...)</code></strong> from the <strong><code>{extRemes}</code></strong> package:</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong><code>return level</code></strong> is the value expected to be exceeded on average <strong>once every T years</strong>.</p>
</div>
</div>
</div></div><div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># specific return periods (e.g., 10, 20 years)</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>rperiods <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">50</span>, <span class="dv">100</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co"># compute return levels (with 95% confidence intervals)</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>rlevels <span class="ot">=</span> <span class="fu">return.level</span>(sgp_fit, <span class="at">return.period=</span>rperiods, <span class="at">do.ci=</span><span class="cn">TRUE</span>)</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a><span class="co"># print results</span></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(rlevels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>fevd(x = x, threshold = thres, type = "GP", method = "GMLE", 
    time.units = paste0(units, "/year"))

[1] "Normal Approx."

                      95% lower CI Estimate 95% upper CI
2-year return level       18.33132 20.14264     21.95396
5-year return level       23.30110 27.34035     31.37960
10-year return level      27.12648 34.31731     41.50814
20-year return level      30.77529 42.96605     55.15681
50-year return level      34.81016 57.65826     80.50637
100-year return level     36.68461 71.89985    107.11510</code></pre>
</div>
</div>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong><code>sgp_fit object</code></strong> is the object returned by the <strong><code>fevd(...)</code></strong> function when we have fitted a the <strong>stationary GP model</strong>.</p>
</div>
</div>
</div></div></section>
<section id="non-stationary-context" class="level2 page-columns page-full" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="non-stationary-context"><span class="header-section-number">10.2</span> Non-Stationary context</h2>
<p>In non-stationary context, since the <strong>scale parameter is time-dependent</strong>, <strong>return levels</strong> have to be calculated for each time step. We refer to this as <strong><code>“effective” return levels</code></strong>The same <strong><code>return.level(...)</code></strong> from the <strong><code>{extRemes}</code></strong> package is used to compute <strong><code>"effective" return levels</code></strong>.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <strong><code>nsgp_fit object</code></strong> is the object returned by the <strong><code>fevd(...)</code></strong> function when we have fitted a the <strong>non-stationary GP model</strong>.</p>
</div>
</div>
</div></div><div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># specific return periods (e.g., 10, 20 years)</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>rperiods <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">20</span>, <span class="dv">50</span>, <span class="dv">100</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co"># compute return levels (with 95% confidence intervals)</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>rlevels <span class="ot">=</span> <span class="fu">return.level</span>(nsgp_fit, <span class="at">return.period=</span>rperiods)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For easy visualization, we will plot the <strong><code>effective return levels</code></strong>. Lets convert the output of <strong><code>return.level(...)</code></strong> into a clean data.frame :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert estimates to data.frame</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>df_rlevels <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">time=</span><span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(peaks_final),</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Q2=</span>rlevels[, <span class="dv">1</span>],</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Q5=</span>rlevels[, <span class="dv">2</span>],</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Q10=</span>rlevels[, <span class="dv">3</span>],</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Q20=</span>rlevels[, <span class="dv">4</span>],</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Q50=</span>rlevels[, <span class="dv">5</span>],</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Q100=</span>rlevels[, <span class="dv">6</span>])</span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df_rlevels)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  time       Q2       Q5      Q10      Q20      Q50     Q100
1    1 21.36000 29.38540 37.14447 46.74100 63.00002 78.71949
2    2 21.34887 29.36640 37.11788 46.70500 62.94809 78.65216
3    3 21.33774 29.34741 37.09128 46.66901 62.89617 78.58484
4    4 21.32661 29.32842 37.06469 46.63301 62.84424 78.51751
5    5 21.31549 29.30943 37.03810 46.59702 62.79232 78.45019
6    6 21.30436 29.29044 37.01150 46.56102 62.74039 78.38286</code></pre>
</div>
</div>
<p>Now, we tranform the data into a long (tidy) format suitable for plotting multiple lines with <strong><code>ggplot</code></strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>dataplot <span class="ot">=</span> df_rlevels <span class="sc">|&gt;</span> </span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>           <span class="fu">pivot_longer</span>(<span class="sc">-</span><span class="dv">1</span>, <span class="at">names_to=</span><span class="st">"RL"</span>, <span class="at">values_to=</span><span class="st">"Q"</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>           <span class="co"># re-index</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>           <span class="fu">mutate</span>(<span class="at">RL =</span> <span class="fu">factor</span>(RL, <span class="at">levels=</span><span class="fu">rev</span>(<span class="fu">paste0</span>(<span class="st">"Q"</span>, <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">5</span>,<span class="dv">10</span>,<span class="dv">20</span>,<span class="dv">50</span>,<span class="dv">100</span>)))))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Finally, we plot the <strong><code>effective return levels</code></strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>rlplot <span class="ot">=</span> dataplot <span class="sc">|&gt;</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>         <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>time, <span class="at">y=</span>Q, <span class="at">color=</span>RL, <span class="at">group=</span>RL)) <span class="sc">+</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>         <span class="fu">geom_line</span>(<span class="at">linewidth=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>         <span class="fu">scale_x_continuous</span>(<span class="at">expand=</span><span class="fu">c</span>(<span class="fl">0.01</span>, <span class="fl">0.01</span>)) <span class="sc">+</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>         <span class="fu">scale_y_continuous</span>(<span class="at">expand=</span><span class="fu">c</span>(<span class="fl">0.01</span>, <span class="fl">0.01</span>)) <span class="sc">+</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>         <span class="fu">guides</span>(<span class="at">color=</span><span class="fu">guide_legend</span>(<span class="at">keywidth=</span><span class="dv">3</span>)) <span class="sc">+</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>         <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>         <span class="fu">theme</span>(<span class="at">legend.text=</span><span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">12</span>),</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>               <span class="at">axis.title=</span><span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">12</span>),</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>               <span class="at">axis.text=</span><span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">12</span>, <span class="at">color=</span><span class="st">"black"</span>)) <span class="sc">+</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>         <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Time"</span>, <span class="at">y=</span><span class="st">"Return level (Q)"</span>, <span class="at">color=</span><span class="cn">NULL</span>)</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>           </span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(rlplot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><a href="#fig-effective-return-levels" class="quarto-xref">Figure&nbsp;11</a> helps in understanding the variations and trends in flood quantiles across different time periods.”</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-effective-return-levels" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-effective-return-levels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-effective-return-levels-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-effective-return-levels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Effective return levels from the NS-GEV model. Each line represents a different return period (e.i., 2-, 5-, 10-, 20 50, and 100-year floods), and the colour coding indicates these return periods. The x-axis denotes the time index (year), and the y-axis indicates the estimated flood quantiles.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="references" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-coles2001" class="csl-entry" role="listitem">
Coles, S. (2001). <em>An introduction to statistical modeling of extreme values</em> (p. 208). Springer.
</div>
<div id="ref-cunnane1979" class="csl-entry" role="listitem">
Cunnane, C. (1979). A note on the poisson assumption in partial duration series models. <em>Water Resources Research</em>, <em>15</em>(2), 489–494.
</div>
<div id="ref-gilleland2016extremes" class="csl-entry" role="listitem">
Gilleland, E., &amp; Katz, R. W. (2016). extRemes 2.0: An extreme value analysis package in <span>R</span>. <em>Journal of Statistical Software</em>, <em>72</em>(8), 1–39. <a href="https://doi.org/10.18637/jss.v072.i08">https://doi.org/10.18637/jss.v072.i08</a>
</div>
<div id="ref-lang1999" class="csl-entry" role="listitem">
Lang, M., Ouarda, T. B. M. J., &amp; Bobée, B. (1999). Towards operational guidelines for over-threshold modeling. <em>Journal of Hydrology</em>, <em>225</em>(3-4), 103–117. <a href="https://doi.org/10.1016/S0022-1694(99)00167-5">https://doi.org/10.1016/S0022-1694(99)00167-5</a>
</div>
<div id="ref-ribatet2011pot" class="csl-entry" role="listitem">
Ribatet, M. A. (2011). <em>A user guide to the POT package (version 1.4)</em>. <a href="https://cran.r-project.org/package=POT">https://cran.r-project.org/package=POT</a>
</div>
<div id="ref-solari2017" class="csl-entry" role="listitem">
Solari, S., Egüen, M., Polo, M. J., &amp; Losada, M. A. (2017). Peaks over threshold (POT): A methodology for automatic threshold estimation using goodness of fit p-value. <em>Water Resour. Res.</em>, <em>53</em>, 2833–2849. <a href="https://doi.org/10.1002/2016WR019426">https://doi.org/10.1002/2016WR019426</a>
</div>
<div id="ref-wrc1975" class="csl-entry" role="listitem">
USWRC. (1975). <em>Guidelines for determining flood flow frequency</em> (17). US Water Resources Council, Hydrology Committee.
</div>
<div id="ref-wald_test_1940" class="csl-entry" role="listitem">
Wald, A., &amp; Wolfowitz, J. (1940). On a test whether two samples are from the same population. <em>The Annals of Mathematical Statistics</em>, <em>11</em>(2), 147–162. <a href="https://doi.org/10.1214/aoms/1177731909">https://doi.org/10.1214/aoms/1177731909</a>
</div>
</div>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/422774bf-444b-4eea-82c2-98644a70d53e\.netlify\.app\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Copyright 2025</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="http://orcid.org/0000-0003-0481-5330">
<p>Yves Tramblay <i class="fa-brands fa-orcid"></i></p>
</a>
  </li>  
    <li class="nav-item">
 |
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://orcid.org/0009-0002-8743-3660">
<p>Serigne Bassirou Diop <i class="fa-brands fa-orcid"></i></p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
<p>Powered by <a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>